name: "Force Push Artifact To Repo"
description: "A composite action to download an artifact and push it to a target repository.  Automatically includes .binder for notebook pushes"

inputs:
  target_repo_name:
    description: "The name of the target repository"
    required: true
  branch_name:
    description: "The branch name to push to"
    required: false
    default: "main"
  token:
    description: "Personal Access Token for authentication"
    required: true
  artifact_name:
    description: "The name of the artifact to download"
    required: true
  workflow_name:
    description: "The name of the workflow to download the artifact from (e.g., deploy.yml)"
    required: true

runs:
  using: "composite"
  steps:
    # Step 1: Download Artifact
    - name: Download Artifact
      uses: dawidd6/action-download-artifact@v7
      with:
        workflow: ${{ inputs.workflow_name }}
        branch: ${{ inputs.branch_name }}
        name: ${{ inputs.artifact_name }}
        path: artifact

    - name: Clone Target Repository
      shell: bash
      env:
        TARGET_REPO: ${{ inputs.target_repo_name }}
        TOKEN: ${{ inputs.token }}
      run: |
        git clone https://${TOKEN}@github.com/${TARGET_REPO}.git target_repo

    - name: Copy Artifact to Target Repository
      shell: bash
      run: |
        find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +
        cp -r ./artifact/* target_repo/

    - name: Force Push Changes to Target Repository
      shell: bash
      env:
        TARGET_REPO: ${{ inputs.target_repo_name }}
        TOKEN: ${{ inputs.token }}
      run: |
        cd target_repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git add .binder || true
        # Only commit and push if there are changes
        if ! git diff --cached --quiet; then
          git add -A && git commit -m "Update artifact"
          git push --force origin ${{ inputs.branch_name }}
        else
          echo "No changes to commit or push."
        fi        
